replicaCount: 1

image:
  repository: aruncoolprojects/order-service
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30002

#env:
 # inventoryServiceUrl: "http://inventory-service:80"
